name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
    
jobs:
  push_to_registry:
    name: Push Docker iamge to Docker Hub
    runs-on: ubuntu:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME }}
          password: ${{secrests.DOCKER_PASSWORD }}
          
      - name: Extract metadata{tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: itsbijaya/django-todo
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.ouputs.lebels }}
  

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
